//****************************************************************************
//                             File COMPILE.H
//
//                     Miscellaneous switches to compile
//
//      Copyright (c) Dmitry V. Stefankov, 1997. All rights reserved.
//
//****************************************************************************
//
//   $Source: F:/MSVC20/SOURCE/RASKEEPD/RCS/compile.h $
//  $RCSfile: compile.h $
//   $Author: dstef $
//     $Date: 1998/10/03 13:43:35 $
// $Revision: 1.1 $
//   $Locker: dstef $
//
//      $Log: compile.h $
//      Revision 1.1  1998/10/03 13:43:35  dstef
//      Initial revision
//
//
//****************************************************************************

#ifndef _COMPILE_H_
#define _COMPILE_H_


#define   WINSOCK_NT95                      // WinSock support
#define   WIN32_REGISTRY                    // Win32 registry support
#define  _UNICODE                           // UniCode for C runtime library
#define   UNICODE                           // UniCode for WIN32 API


#endif                                      // #ifndef _COMPILE_H_
