//****************************************************************************
//                              File DEBUG.H
//
//                          Debugging definitions
//
//      Copyright (c) Dmitry V. Stefankov, 1997. All rights reserved.
//
//****************************************************************************
//
//   $Source: F:/MSVC20/SOURCE/RASKEEPD/RCS/debug.h $
//  $RCSfile: debug.h $
//   $Author: dstef $
//     $Date: 1998/10/03 13:44:06 $
// $Revision: 1.1 $
//   $Locker: dstef $
//
//      $Log: debug.h $
//      Revision 1.1  1998/10/03 13:44:06  dstef
//      Initial revision
//
//
//****************************************************************************

#ifndef _DEBUG_H_
#define _DEBUG_H_


#define  DebugBreak     _asm  int 0x01


#endif                                      // #ifndef _DEBUG_H_
