//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RASKEEP.RC
//
#define IDC_GENERIC1                    1004
#define IDC_CHECK1                      1015
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         101
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
