# Make CHRCNV for UNIX FreeBSD GNU C/C++ v2.7.2.3

# $Id$

#
# Copyright (c) 2000 Dmitry Stefankov
# Distributed under license by the Free Software Foundation, Inc. (GPL)
#
# This file is part of project CHRCNV.
#

TARGET = chrcnv

#all: $(TARGET)

CC = cc
CFLAGS = -D_UNIX -D_FREEBSD -Wall -m486 -O2 -x c++
MAKEFILE = makefile.bsd

$(TARGET):  $(TARGET).c $(MAKEFILE)
	 $(CC)  $(CFLAGS) -o $(TARGET) $(TARGET).c

clean:
	rm $(TARGET)
