# Make CHRCNV

# $Id: makefile.dj 1.4 2000/01/22 05:28:52 dstef Exp dstef $

# Copyright (c) 1999 Dmitry Stefankov
# Distributed under license by the Free Software Foundation, Inc. (GPL)
#
# This file is part of project CHRCNV.
#

TARGET = chrcnv

#all: $(TARGET).exe

CC = gcc
CFLAGS = -D_UNIX -D_DJGPP -mpentium -O2 -Wall -s -x c++
MAKEFILE = makefile.dj

$(TARGET).exe:  $(TARGET).c $(MAKEFILE)
	$(CC)  $(CFLAGS) -o $(TARGET).exe $(TARGET).c

clean:
	del $(TARGET).exe
  