# Make SLALOM for Borland C/C++ v3.1 for 16-bit MS-DOS

# $Id: makefile.bcc 1.1 2002/01/15 04:10:53 dstef Exp dstef $

#
# Copyright (c) 2002 Dmitry Stefankov
#
# This file is part of project SLALOM.
#

TARGET = slalom

CC     = bcc
CFLAGS = -D_MSDOS -O2
MAKEFILE = makefile.bcc

$(TARGET).exe:  $(TARGET).c  $(MAKEFILE)
	$(CC) $(CFLAGS) $(TARGET).c

clean:
        del $(TARGET).obj
	del $(TARGET).exe
