# Make SHOOTER for GNU C/C++ v3.02 for 32-bit MS-DOS

# $Id: makefile.dj 1.1 2002/01/01 21:44:05 dstef Exp $

#
# Copyright (c) 2001-2002 Dmitry Stefankov
#
# This file is part of project SHOOTER.
#

TARGET = shooter

CC     = gcc
CFLAGS = -D_DJGPP -O2
MAKEFILE = makefile.dj

$(TARGET).exe:  $(TARGET).c  $(MAKEFILE)
	$(CC) $(CFLAGS) -o $(TARGET).exe $(TARGET).c

clean:
	del $(TARGET).exe
